export const GET_MY_USER_LIST_API_REQUEST = 'GET_MY_USER_LIST_REQUEST';
export const GET_MY_USER_LIST_API_STARTED = 'GET_MY_USER_LIST_STARTED';
export const GET_MY_USER_LIST_API_SUCCESS = 'GET_MY_USER_LIST_SUCCESS';
export const GET_MY_USER_LIST_API_FAILURE = 'GET_MY_USER_LIST_FAILURE';
